from typing import TypedDict, List

class Team(TypedDict):
	teamId: str
	city: str
	name: str
	slug: str
	tricode: str
	division: str
	conference: str

class Game(TypedDict):
	gameId: str
	code: str
	dateTimeUTC: str
	dateTimeET: str
	order: int
	statusCode: int
	statusText: str
	livePeriod: int
	liveClock: str
	arena: str
	homeTeamId: str
	awayTeamId: str

class Standing(TypedDict):
	teamId: str
	seasonId: str
	teamCity: str
	conference: str
	division: str
	gamesPlayed: int
	wins: int
	losses: int
	winPct: float
	clinchedConference: bool
	clinchedDivision: bool
	clinchedPlayoff: bool
	clinchedPlayIn: bool
	eliminatedConference: bool
	eliminatedDivision: bool
	conferenceRank: int
	divisionRank: int
	conferenceRecord: str
	divisionRecord: str
	homeRecord: str
	awayRecord: str
	l10Record: str
	homeStreak: int
	awayStreak: int
	pointsFor: int
	pointsAgainst: int

class GameTeam(TypedDict):
	gameId: str
	teamId: str
	teamName: str
	teamCity: str
	teamTricode: str
	score: int
	inBonus: bool
	timeoutsRemaining: int
	periods: List[dict]
	assists: int
	assistsTurnoverRatio: float
	benchPoints: int
	biggestLead: int
	biggestLeadScore: str
	biggestScoringRun: int
	biggestScoringRunScore: str
	blocks: int
	blocksReceived: int
	fastBreakPointsAttempted: int
	fastBreakPointsMade: int
	fastBreakPointsPercentage: float
	fieldGoalsAttempted: int
	fieldGoalsEffectiveAdjusted: float
	fieldGoalsMade: int
	fieldGoalsPercentage: float
	foulsOffensive: int
	foulsDrawn: int
	foulsPersonal: int
	foulsTeam: int
	foulsTechnical: int
	foulsTeamTechnical: int
	freeThrowsAttempted: int
	freeThrowsMade: int
	freeThrowsPercentage: float
	leadChanges: int
	minutes: str
	points: int
	pointsAgainst: int
	pointsFastBreak: int
	pointsFromTurnovers: int
	pointsInThePaint: int
	pointsInThePaintAttempted: int
	pointsInThePaintMade: int
	pointsInThePaintPercentage: float
	pointsSecondChance: int
	reboundsDefensive: int
	reboundsOffensive: int
	reboundsPersonal: int
	reboundsTeam: int
	reboundsTeamDefensive: int
	reboundsTeamOffensive: int
	reboundsTotal: int
	secondChancePointsAttempted: int
	secondChancePointsMade: int
	secondChancePointsPercentage: float
	steals: int
	teamFieldGoalAttempts: int
	threePointersAttempted: int
	threePointersMade: int
	threePointersPercentage: float
	timeLeading: str
	timesTied: int
	trueShootingAttempts: float
	trueShootingPercentage: float
	turnovers: int
	turnoversTeam: int
	turnoversTotal: int
	twoPointersAttempted: int
	twoPointersMade: int
	twoPointersPercentage: float

class GamePlayer(TypedDict):
	gameId: str
	playerId: str
	teamId: str
	firstName: str
	lastName: str
	status: str
	order: int
	jerseyNum: str
	startingPosition: str
	starter: bool
	oncourt: bool
	played: bool
	assists: int
	blocks: int
	blocksReceived: int
	fieldGoalsAttempted: int
	fieldGoalsMade: int
	fieldGoalsPercentage: float
	foulsOffensive: int
	foulsDrawn: int
	foulsPersonal: int
	foulsTechnical: int
	freeThrowsAttempted: int
	freeThrowsMade: int
	freeThrowsPercentage: float
	minus: float
	minutes: str
	plus: float
	plusMinusPoints: float
	points: int
	pointsFastBreak: int
	pointsInThePaint: int
	pointsSecondChance: int
	reboundsDefensive: int
	reboundsOffensive: int
	reboundsTotal: int
	steals: int
	threePointersAttempted: int
	threePointersMade: int
	threePointersPercentage: float
	turnovers: int
	twoPointersAttempted: int
	twoPointersMade: int
	twoPointersPercentage: float
	
class PlayerSeasonAverages(TypedDict):
    playerId: str
    playerName: str
    playerAge: int
    teamId: str
    teamTricode: str
    gamesPlayed: int
    wins: int
    losses: int
    winPercentage: float
    minutes: float
    fieldGoalsMade: int
    fieldGoalsAttempted: int
    fieldGoalsPercentage: float
    threePointersMade: int
    threePointersAttempted: int
    threePointersPercentage: float
    freeThrowsMade: int
    freeThrowsAttempted: int
    freeThrowsPercentage: float
    reboundsOffensive: int
    reboundsDefensive: int
    reboundsTotal: int
    assists: int
    turnovers: int
    steals: int
    blocks: int
    blocksReceived: int
    foulsPersonal: int
    foulsDrawn: int
    points: int
    plusMinusPoints: float
    fantasyPoints: float
    doubleDoubles: int
    tripleDoubles: int
    gamesPlayedRank: int
    winsRank: int
    lossesRank: int
    winPercentageRank: int
    minutesRank: int
    fieldGoalsMadeRank: int
    fieldGoalsAttemptedRank: int
    fieldGoalsPercentageRank: int
    threePointersMadeRank: int
    threePointersAttemptedRank: int
    threePointersPercentageRank: int
    freeThrowsMadeRank: int
    freeThrowsAttemptedRank: int
    freeThrowsPercentageRank: int
    reboundsOffensiveRank: int
    reboundsDefensiveRank: int
    reboundsTotalRank: int
    assistsRank: int
    turnoversRank: int
    stealsRank: int
    blocksRank: int
    blocksReceivedRank: int
    foulsPersonalRank: int
    foulsDrawnRank: int
    pointsRank: int
    plusMinusPointsRank: int
    fantasyPointsRank: int
    doubleDoublesRank: int
    tripleDoublesRank: int

	